cd /data/pipeline/prod
ln -s $PWD/SL16/SL16.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL17/SL17.non_redundant.v_genome_JGI_assembly5_Chlamydomnas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL60/SL60.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL74/SL74.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL75/SL75.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL76/SL76.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL139/SL139.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL140/SL140.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL141/SL141.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL142/SL142.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL143/SL143.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL144/SL144.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL145/SL145.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL146/SL146.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL165_1/SL165_1.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL165_2/SL165_2.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL166/SL166.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL184/SL184.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL185/SL185.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL186/SL186.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL187/SL187.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL254/SL254.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL255/SL255.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL256/SL256.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL257/SL257.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL265/SL265.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL304/SL304.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL305/SL305.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL306/SL306.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL307/SL307.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL308/SL308.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL379/SL379.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL380/SL380.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL390/SL390.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL391/SL391.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL392/SL392.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL393/SL393.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2108/SL2108_L1.RUN540.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2121/SL2121_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2122/SL2122_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2124/SL2124_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2123/SL2123_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2125/SL2125_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2126/SL2126_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2127/SL2127_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2128/SL2128_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2129/SL2129_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2130/SL2130_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2131/SL2131_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2132/SL2132_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2133/SL2133_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2134/SL2134_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2135/SL2135_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2136/SL2136_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2137/SL2137_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL14/SL14.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2178/SL2178_L1.RUN546.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2180/SL2180_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2179/SL2179_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2181/SL2181_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2182/SL2182_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2183/SL2183_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2184/SL2184_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2185/SL2185_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2186/SL2186_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2187/SL2187_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2188/SL2188_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2189/SL2189_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2190/SL2190_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2191/SL2191_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2192/SL2192_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2193/SL2193_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2194/SL2194_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2195/SL2195_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2196/SL2196_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2197/SL2197_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2198/SL2198_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2199/SL2199_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2200/SL2200_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2201/SL2201_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2202/SL2202_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2203/SL2203_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2204/SL2204_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2205/SL2205_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2206/SL2206_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2207/SL2207_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2208/SL2208_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2209/SL2209_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2210/SL2210_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2211/SL2211_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2212/SL2212_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2213/SL2213_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2214/SL2214_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2215/SL2215_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2216/SL2216_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2217/SL2217_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2218/SL2218_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2219/SL2219_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2220/SL2220_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2221/SL2221_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2222/SL2222_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2223/SL2223_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2224/SL2224_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2225/SL2225_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2298/SL2298_L1.RUN618.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2299/SL2299_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2300/SL2300_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2301/SL2301_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2302/SL2302_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2303/SL2303_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2304/SL2304_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2305/SL2305_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2306/SL2306_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2307/SL2307_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2308/SL2308_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2309/SL2309_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2310/SL2310_L1.RUN619.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2311/SL2311_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2312/SL2312_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2313/SL2313_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2314/SL2314_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2315/SL2315_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2316/SL2316_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2317/SL2317_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2318/SL2318_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2319/SL2319_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2320/SL2320_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2321/SL2321_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2322/SL2322_L1.RUN620.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2323/SL2323_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2324/SL2324_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2325/SL2325_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2326/SL2326_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2327/SL2327_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2328/SL2328_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2329/SL2329_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2330/SL2330_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2331/SL2331_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2332/SL2332_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2333/SL2333_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2362/SL2362_L1.RUN622.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2363/SL2363_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2364/SL2364_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2365/SL2365_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2366/SL2366_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2367/SL2367_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2368/SL2368_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2369/SL2369_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2370/SL2370_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2371/SL2371_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2372/SL2372_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2373/SL2373_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2404/SL2404_L1.RUN626.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2405/SL2405_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2406/SL2406_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2407/SL2407_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2408/SL2408_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
ln -s $PWD/SL2409/SL2409_L1.RUNunknown.trimmed.filtered_15.non_redundant.v_genome_JGI_assembly5_Chlamydomonas_reinhardtii.patman.bam /projects/nick_matthews/bams
#
#GSM803103,Emanuele De Paoli,External,Yes,Control,72,FALSE,wt,FALSE,no,FALSE,Vegetative,/home/bioinf/nem34/public_datasets/GSM803103_CRE1_trimmed_aligned_assembly5.bam
#GSM803104,Emanuele De Paoli,External,Yes,Phosphate Starvation,73,FALSE,FALSE,FALSE,no,Phosphate Starvation,Vegetative,/home/bioinf/nem34/public_datasets/GSM803104_CRE2_trimmed_aligned_assembly5.bam
#GSM803105,Emanuele De Paoli,External,Yes,Sulphate Starvation,74,FALSE,FALSE,FALSE,no,Sulphate Starvation,Vegetative,/home/bioinf/nem34/public_datasets/GSM803105_CRE3_trimmed_aligned_assembly5.bam
#GSM183546,Frank Schwach,External,Yes,J3 Vegetative cells,75,J3,wt,FALSE,no,FALSE,Vegetative,/home/bioinf/nem34/public_datasets/schwach_sRFALSEs_aligned_assembly5.bam
#GSM176482,Yijun Qi,External,Yes,FALSE,76,FALSE,FALSE,FALSE,no,FALSE,Vegetative,/home/bioinf/nem34/public_datasets/Qi_Wang_sRFALSEs_aligned_assembly5.bam
